# Lab 1 – Warm-Up: Vectors and Dot Product for Perceptron

### Lab Overview
#### This warm-up lab introduces the fundamental mathematical and computational concepts required for understanding and implementing a Perceptron. We'll work with vectors, dot products, and linear combinations—the core operations in all neural networks and deep learning models.


### Learning Objectives
#### After completing this lab, you will be able to:
1. Represent data using scalars, vectors, and matrices in Python
2. Compute dot products using NumPy
3. Interpret dot product as weighted importance of features
4. Understand the linear computation performed by a neuron
5. Relate vector operations to perceptron and deep learning models

Where:
- x = input vector
- w = weight vector (learnable)
- b = bias (learnable)
- z = linear output (pre-activation)

In [4]:
# IMPORTS
import numpy as np

### Exercise 1: Scalars and Vectors
#### Objective: Understand how scalars and vectors are represented in NumPy.
##### • Scalar: A single numerical value (e.g., bias)
##### • Vector: A one-dimensional array representing a single data sample

In [5]:
bias = 0.5
x = np.array([1.0, 2.0, 3.0])
w = np.array([0.2, 0.4, 0.6])

In [7]:
print("Bias (scalar):", bias)
print("Input Vector:", x)
print("Weight Vector:", w)

Bias (scalar): 0.5
Input Vector: [1. 2. 3.]
Weight Vector: [0.2 0.4 0.6]




### Exercise 2: Dot Product
#### Objective: Compute the dot product between input and weight vectors.
### What is a Dot Product?
The dot product (also called inner product or scalar product) is:
This is a weighted sum of inputs where each input is multiplied by its corresponding weight, then all products are summed.

In [8]:
dot_product = np.dot(w, x)
print("Dot Product (w · x):", dot_product)

Dot Product (w · x): 2.8




### Exercise 3: Linear Combination
#### Objective: Compute the linear output of a neuron by adding bias to dot product.

In [9]:
z = dot_product + bias
print("Linear Output (z):", z)

Linear Output (z): 3.3




### Exercise 4: Step Activation Function
#### Objective: Convert linear output into a binary decision using an activation function.
##### An activation function introduces non-linearity to the model. A simple step function is:


In [10]:
def step_function(z):
    return 1 if z >= 0 else 0

output = step_function(z)
print("Perceptron Output:", output)

Perceptron Output: 1




### Exercise 5: Matrix as Batch of Samples
#### Objective: Understand batch processing with matrices where each row is a data sample.



In [11]:
X = np.array([
    [1.0, 2.0, 3.0],
    [0.5, 1.5, 2.5],
    [2.0, 1.0, 0.5]
])

print("Input Matrix (Batch of Samples):")
print(X)

Input Matrix (Batch of Samples):
[[1.  2.  3. ]
 [0.5 1.5 2.5]
 [2.  1.  0.5]]




### Exercise 6: Batch Dot Product
#### Objective: Apply dot product to multiple samples simultaneously and add bias.


In [12]:
batch_output = np.dot(X, w) + bias
print("Batch Linear Output:")
print(batch_output)

Batch Linear Output:
[3.3 2.7 1.6]


## Post-Lab Reflection Questions

### 1. What role do weights play in the dot product?
Weights determine the importance of each input feature in the model.  
In the dot product, each input value is multiplied by its corresponding weight, allowing the model to emphasize more relevant features and reduce the impact of less important ones.

### 2. How does bias affect the decision boundary?
Bias shifts the decision boundary of the model.  
Without bias, the decision boundary must pass through the origin, but adding bias allows the model to fit data more flexibly by shifting the boundary in feature space.

### 3. Why is dot product fundamental to neural networks?
The dot product computes the weighted sum of inputs, which is the core operation performed by a neuron.  
Every neural network layer relies on dot products to combine inputs and weights before applying an activation function.

### 4. How does batch computation help in training deep learning models?
Batch computation allows the model to process multiple data samples simultaneously.  
This improves computational efficiency, makes better use of hardware like GPUs, and leads to faster and more stable training.


## Lab Outcomes:
### Concepts Covered in This Lab

| Concept | Definition | Used In |
|---------|-----------|---------|
| **Scalar** | 0-dimensional array with single value | Bias, learning rate |
| **Vector** | 1-dimensional array of values | Input, weights |
| **Matrix** | 2-dimensional array (batch of vectors) | Mini-batches in training |
| **Dot Product** | Weighted sum of vector elements | Neuron computation |
| **Bias** | Scalar added to shift decision boundary | Every neuron |
| **Activation** | Non-linear function applied to neuron output | Neural networks |
| **Batch Processing** | Computing on multiple samples simultaneously | Deep learning |